eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka
      
server:
  port: 8764
  
spring:
  application:
    name: eshop-inventory-service
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://192.168.229.31:3306/eshop
    username: root
    password: root